services:
  postgres:
    image: postgres:16
    container_name: scheduler-postgres
    environment:
      POSTGRES_USER: vivek
      POSTGRES_PASSWORD: password
      POSTGRES_DB: schedulerdb
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: scheduler-redis
    ports:
      - "6379:6379"